### ISSUE TITLE
I3D

### ISSUE THREAD

**Issue by CBHXuTT** [oulutan/ACAM_Demo#12]
why the I3D is cuted on Mixed_4f?

**Comment by oulutan** [comment]
Sorry for the late reply, I was traveling. We cut the I3D on Mixed_4f to be comparable with [this paper.](https://arxiv.org/abs/1807.10066). As we don't have the resources, we did not have time to experiment on this. Training each model takes about 2 weeks on 4x1080Ti GPUs. We only experimented with Mixed_4e similar to [original ava paper](https://arxiv.org/pdf/1705.08421.pdf), but Mixed_4f performed better.

**Comment by CBHXuTT** [comment]
> Sorry for the late reply, I was traveling. We cut the I3D on Mixed_4f to be comparable with [this paper.](https://arxiv.org/abs/1807.10066). As we don't have the resources, we did not have time to experiment on this. Training each model takes about 2 weeks on 4x1080Ti GPUs. We only experimented with Mixed_4e similar to [original ava paper](https://arxiv.org/pdf/1705.08421.pdf), but Mixed_4f performed better.

Thank you for your reply!
