### ISSUE TITLE
May I ask when to release the training script?

### ISSUE THREAD

**Issue by lllsiriuslll** [oulutan/ACAM_Demo#13]
Hi.
Thank you for your work, 
I confirmed your demo. Very impressive!
I would like to use your method for training,  may I ask when the training script will be released?

Thanks.

**Comment by oulutan** [comment]
Thank you! 
As currently I  don't have much time and the paper is not published officially, we decided to keep the training code private until it is published. Sorry for the inconvenience.

**Comment by lllsiriuslll** [comment]
@oulutan 
Thank you for reply.
I look forward your training script will be released!

Thanks.
