### ISSUE TITLE
training and evaluation codes?

### ISSUE THREAD

**Issue by abc67ok** [oulutan/ACAM_Demo#18]
Dear
     when will you release the training and evaluation codes? Thank you for your great work.

**Comment by abc67ok** [comment]
Dear
     what dateset have you used for training ? like model_ckpt_soft_attn_pooled_cosine_drop_ava-130.

**Comment by oulutan** [comment]
It uses the AVA dataset for training. 

As I said in the previous issues, I will be releasing the training code when the paper is published.
