### ISSUE TITLE
annotating new videos

### ISSUE THREAD

**Issue by usuyama** [oulutan/ACAM_Demo#22]
Thanks for posting a great demo!

Do you have any recommendations for annotation tools? I'm looking for a tool for annotating some of my videos.

**Comment by oulutan** [comment]
Vatic is one example. But this is quite old, Im sure there are much better ones now. 
https://github.com/cvondrick/vatic

**Comment by usuyama** [comment]
Thanks, @oulutan! 

I looked around the web, and found VoTT https://github.com/microsoft/VoTT#labeling-a-video looks useful for my application. VoTT only supports frame-by-frame annotations for videos, but it's works okay because actions that I'm interested have similar temporal length. I hope they can support temporal segment annotation properly though.
