### ISSUE TITLE
ImportError: No module named tools.generate_detections

### ISSUE THREAD

**Issue by harishankards** [oulutan/ACAM_Demo#27]
I followed all the methods which are provided in the documentation. But while running `python detect_actions.py`, I ran into the following issue. Please help!
```
Traceback (most recent call last):
  File "detect_actions.py", line 11, in <module>
    import object_detection.object_detector as obj
  File "/home/hs/Spritle/siemens/ACAM_Demo/object_detection/object_detector.py", line 64, in <module>
    from tools.generate_detections import create_box_encoder
ImportError: No module named tools.generate_detections

```

**Comment by zlstl1** [comment]
# From object_detection/models/research/
source SET_ENVIRONMENT.sh

**Comment by Emnaa12** [comment]
I got the same error. Could you tell me how did you resolve it? (I am working on Colab)
