### ISSUE TITLE
when release training code 

### ISSUE THREAD

**Issue by autocyz** [oulutan/ACAM_Demo#3]
Thank you for your work, especially for your open code. I really want to use this to my own project, so could you please tell when you will open your training code?

**Comment by oulutan** [comment]
I am still working to clean it up. There is still a lot to do on the training code for releasing and I am busy with other things. I would guess I can release it in two-three weeks. I will post it here when it is released. Thanks for the interest.

**Comment by songjd** [comment]
Thank you for your work, especially for your open code.
