### ISSUE TITLE
AttributeError: 'Track' object has no attribute 'last_detection_confidence'

### ISSUE THREAD

**Issue by NaeemKhan333** [oulutan/ACAM_Demo#32]
Thanks For Nice Work . I am testing my videos on the pre-trained weights . I have run the following command

python detect_actions.py --video_path=output.mp4 

But After running for some frames, It Give me following error

Instructions for updating:
Use standard file APIs to check for files with this prefix.
frame_cnt: 1
obj det 3.26 seconds
tracker 0.00 seconds
frame_cnt: 2
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 3
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 4
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 5
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 6
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 7
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 8
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 9
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 10
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 11
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 12
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 13
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 14
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 15
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 16
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 17
obj det 0.08 seconds
tracker 0.00 seconds
frame_cnt: 18
obj det 0.11 seconds
tracker 0.00 seconds
frame_cnt: 19
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 20
obj det 0.10 seconds
tracker 0.00 seconds
frame_cnt: 21
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 22
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 23
obj det 0.09 seconds
tracker 0.00 seconds
frame_cnt: 24
obj det 0.08 seconds
tracker 0.19 seconds
frame_cnt: 25
obj det 0.09 seconds
tracker 0.01 seconds
frame_cnt: 26
obj det 0.08 seconds
tracker 0.01 seconds
frame_cnt: 27
obj det 0.09 seconds
tracker 0.01 seconds
frame_cnt: 28
obj det 0.08 seconds
Traceback (most recent call last):
  File "detect_actions.py", line 308, in <module>
    main()
  File "detect_actions.py", line 97, in main
    tracker.update_tracker(detection_info, cur_img)
  File "/home/user/Downloads/ACAM_Demo-master/object_detection/object_detector.py", line 166, in update_tracker
    detection_conf = track.last_detection_confidence
AttributeError: 'Track' object has no attribute 'last_detection_confidence'

Can you guide me about error . Thank you

**Comment by oulutan** [comment]
Looks like no object has been detected. Did you solve this?

**Comment by NaeemKhan333** [comment]
Yeah , I solve this problem as follow 
1- Go to "ACAM_Demo-master/object_detection/object_detector.py" and Open it
2- On line 167 

Replace

```
detection_conf = track.last_detection_confidence
```

With

```
detection_conf = 0
```
This issue Will be resolved.

**Comment by NaeemKhan333** [comment]
![Screenshot from 2020-02-19 17-59-33](https://user-images.githubusercontent.com/52487215/74836958-46dc2180-5342-11ea-80cd-513540a609e9.png)
