### ISSUE TITLE
Training Model on Custom Dataset

### ISSUE THREAD

**Issue by NaeemKhan333** [oulutan/ACAM_Demo#33]
Thank you for very nice work . I want to training my own data set ,which have 4 classes and I have 200 videos for every class . Can anybody Guide me what steps I need to do to train my own data set using this technique .Does I need to do annotation for every video or there is any other way which I need to adopt to train my own data set on this technique.  Please give a complete overview for training my own data set. Thank you

**Comment by oulutan** [comment]
Training code has been available here for past 2 months. 

https://github.com/oulutan/ActorConditionedAttentionMaps

**Comment by NaeemKhan333** [comment]
Thanks for your reply, We know Training code is available but we cannot figure out how actually pre-processed and structure our data set to train on the given data set. Can you briefly guide about this .Thanks
