### ISSUE TITLE
Limit of 14 actors

### ISSUE THREAD

**Issue by AVCarreiro** [oulutan/ACAM_Demo#6]
Hello, first of all let me congratulate you on your work, and thank you for sharing it!

Quick question: 
  - I see you limit the number of actors to 14 (in both detect_actions.py and multiprocess_detect_actions.py). Just not to increase memory usage or other specific reason?

Thanks

**Comment by oulutan** [comment]
Hi, Thank you!

Yes, When I was running it on crowded surveillance videos, I was getting GPU out of memory error in action detection part. This was a quick fix to resolve that. ROIs are already sorted by their confidence scores so I decided to take the top 14 in that case. 

If you want support for more actors, you can change that part with a for loop and combine "probs" vectors afterwards. Everything should work without issues but you will get a slow down on performance as you need to run action detector multiple times each time.
